### ISSUE TITLE
sys.h missing

### ISSUE THREAD

**Issue by tiithe** [vortex314/mqtt2serial#2]
I tried mqtt2serial, but the sys.h seems to be missing. I can't compile it. 
Thanks..

Tiit

**Comment by vortex314** [comment]
Hi tiithe, thanks for the interest and feedback. I'm guessing you took one of the projects with platformio.ini. 
You will notice that in these config files, the include refers to other directories :
    -I../../Common 
    -Wl,-Map,output.map 
    -I../../nanoAkka/main
    -I../../nanoAkka/components/wifi
    -I../../ArduinoJson/src
So it means that you have to clone some other projects like Common and nanoAkka.
git clone https://github.com/vortex314/nanoAkka.git
git clone https://github.com/vortex314/Common.git
git clone https://github.com/bblanchon/ArduinoJson

Hope this helps, let me know how it goes. I will add later in the README.MD the build instructions.
Lieven

**Comment by vortex314** [comment]
Build instructions have been added to README.MD. Let me know if it works.

**Comment by tiithe** [comment]
OK .. it is better now, but now is Mqttserial.h missing :) There is a link in esp2866 src, but no file itself. It may be my configuration problem .. I check it.
Tiit

**Comment by vortex314** [comment]
Sorry my bad, I didn't compile the esp8266 version for a long time. Corrected, should work. 
Don't forget to follow the build instructions in readme. It requires some files from other repo's.
Keep me posted. 
Lieven

**Comment by vortex314** [comment]
No more feedback.
