### ISSUE TITLE
Arduino Nano as slave device (Analog? I2C?)

### ISSUE THREAD

**Issue by PizzaProgram** [vortex314/mqtt2serial#3]
Hi,
 This project seems to be what I'm looking for since a year long :) !

I don't like "wifi" things, because a "dry-lightning" killed everything in my house anyhow involved with non-shielded cables or antennas and everything indirectly attacked to them. Shielded USB and FTP cables are more secure.

I have a Raspberry Pi4 running as a home automation server.
- Also MQTT Mosquito runs on it.
- and NodeRed too.

But I can not communicate with all those [Arduino Nano](https://store.arduino.cc/arduino-nano?queryID=undefined) boards' pins attached to it with USB ports. (And later maybe some other with Ethernet port.)

I've tried to flash Firmata on them first, but it's not working. (NodeRed example does not connects.)
MQTT would be more ideal for a whole house. (80 inputs=buttons, 60 relays, sensors, ...)

What I do not find here, is an .INO file I could :
- edit a bit **in Arduino IDE** on my Laptop, _to set which pin is what, what should be the board identifier name, etc..._
- compile and upload the firmware to the NANO board, and finally
- attach to the RPi and manage all the inputs and outputs from OpenHAB or NodeRed's MQTT.
... (later maybe also the analog ports and I2C bus attached extended pins)

**Is it possible to do that with this code, or did I misunderstood something completely?**  
  
 (I'm just an average delphi/pascal programmer living in a tiny poor country, but I'm willing to donate too, if it would finally work!)

**Comment by vortex314** [comment]
Is this what you're looking for  : https://github.com/vortex314/mqtt2serial/blob/master/simple/src/main.cpp ?
rename the main.cpp to main.ino and it should work. 
It's the most basic example of just publishing the Arduino local uptime. 

Maybe another fun factor : https://github.com/vortex314/joystick2mqtt

**Comment by PizzaProgram** [comment]
Thanks for the quick respond! :)
Basically **yes**, that's what I was "looking for", I've just hoped there would be a "more complex" client-side example too.  
Where I can also see how a client receives MQTT commands from your mqtt2serial demon and process it as an actual command.
  
Basically an All-in-1 full example would show the word **how it works:**
- Initialize the pins to default
- subscribe
- waits for any MQTT commands received
- > if incoming > switch a pin to HIGH/LOW or analog to 0-255.
- while sending pin-state changes back  
- > if (IO or analog) pin state changes > sends state back (within an interval, so it's not flooding)

Something similar what Firmata does. (See at Arduino IDE: Examples > Firmata > FirmataStandard)

You have wrote "one side" of the task, but without "the other" it's hard to make it actually work in a real life scenarios.
 ... or am I missing something and are there any other full-examples of the client side for Arduino?

Thanks a lot! :)

**Comment by PizzaProgram** [comment]
I'd also would like to recommend to reorganise your folder structure.
# Client examples
  - simple timeup
  - digital IO
  - analog IO
  - I2C
  - complex 
# Master daemon
 - boards
 - doc
 - source
 - etc ...
  
So basically to separate the two sides currently mixed up.  
To goal for that is to make a bit more understandable to everyone visiting this project in the future.

**Comment by vortex314** [comment]
Looks like you give me much higher ambitions then I intended for.  
As this is developed for my own scope , it meets my own needs. Feel free to use. 

A more complex example is here : https://github.com/vortex314/mqtt2serial/blob/master/maple/src/main.cpp
It supports basic DigitalIn/Out and was tested on STM32 Maple in Arduino mode. 

Some non-basic driver examples in that sense can be found here : https://github.com/vortex314/nanoAkka/tree/master/components
They are not the most simple devices to read or drive and are ESP32 specific : motors, steppers, gps, ultrasonic,..

The nanoAkka framework runs on Arduino platform and esp-idf. The components on top are not necessarily interchangeable.

BTW : I don't think you should put the low level DigitalIO as target. It should be an higher abstraction level , example : Steering angle, motor RPM, DWM1000 distance location,...

**Comment by vortex314** [comment]
Some timing measurements :
![image](https://user-images.githubusercontent.com/5508735/103320556-0e16d980-4a36-11eb-9d50-6fc7ccda61da.png)
- this is a ESP32 on a serial connection at 115200 baud, with a broker running on a PC,  loopback time in msec  +/- 20 msec.
- Running at 921600 or 400kb made it slower. After some time the latency went up, restarting serial2mqtt brought it down again. 
- A test with a loopback directly on a Raspberry pi with Mosquitto : 2 msec
-Working at higher serial speeds makes it slow down, strange..

**Comment by vortex314** [comment]
The code of the loopback test.
```
class EchoTest : public Actor {
 public:
  TimerSource trigger;
  ValueSource<uint64_t> counter;
  ValueSource<uint32_t> delta;
  EchoTest(Thread &thread)
      : Actor(thread), trigger(thread, 1000, true, "trigger"){};
  void init() {
    trigger >> [&](const TimerMsg &tm) {
      INFO(" send ");
      counter = Sys::millis();
    };
    counter >> mqtt.toTopic<uint64_t>("echo/output");
    delta >> mqtt.toTopic<uint32_t>("echo/delta");
    mqtt.fromTopic<uint64_t>("src/gps/echo/output") >> [&](const uint64_t in) {
      delta = Sys::millis() - in;
      INFO(" it took %u msec ", delta());
    };
  }
};
```

**Comment by vortex314** [comment]
Some additional testing , showed that sharing the thread between mqtt and the echo actor was not a good idea on the ESP32. Taking a separate thread give more consistent and better results : 17msec

![image](https://user-images.githubusercontent.com/5508735/103320921-8cc04680-4a37-11eb-90bf-f05f0b001419.png)

**Comment by PizzaProgram** [comment]
**Thank you** for the detailed tests! :)
17ms seems fast enough for average usage, like a button-press by a human or sensor readings.
I'll keep on searching for a way to make your work more universal to make it popular, but I'm focusing on non-ESP32 systems.
[Here...](https://discourse.nodered.org/t/mqtt-with-arduino-nano-nodered/37351/24?u=pizzaprogram) you may read more about the current state of my research.

I've also learned enough since opened this topic to know now:
 - reading I2C values from sensors must happen on the Arduino side.
 - easier to import a ready-to-use library for that and forward the value with your layer.
 - it would be too complicated to write a "direct MQTT/I2C translation" layer to handle everything on the server side.

**Comment by vortex314** [comment]
No open issue anymore.
