### ISSUE TITLE
MqttSerial.h is missing. Please could we have it?

### ISSUE THREAD

**Issue by SimonMerrett** [vortex314/mqtt2serial#4]
Hi, I realise that you are just helping out and this was for your own satisfaction - I'm really grateful to have found it. In a closed issue #2 you mentioned fixing the missing MqttSerial.h for esp8266. I cannot see it anywhere. Would you mind uploading please? I would like to try the non-threaded way as I think that will be best for integration with my existing code.

**Comment by vortex314** [comment]
Hi, I reworked the build process , there is now another dependency. 
```
git clone https://github.com/bblanchon/ArduinoJson
git clone https://github.com/vortex314/mqtt2serial.git
git clone https://github.com/vortex314/limero.git
```
platformio doesn't permit to point to other directories , so I had to create symbolic links in the src directory.
I didn't test this yet on a clean system. Let me know how this goes.

I tested this with esp8266, esp32 via serial, esp32 via bluetooth. 
The code is overall the same for all Arduino models. 

Lieven

**Comment by SimonMerrett** [comment]
Ah, I'm not using pio. I considered going back to the time when MqttSerial.h was part of the library and using MqttSerial.cpp from that time too. But I presume you have fixed bugs since then so best not to go back there. I am managing to use Arduino String functions like .indexOf() and .substring() to achieve what I want with no more overhead or code than using an Arduino mqtt library. It's wonderful that you have such a flexible tool in serial2mqtt that I don't have to be able to make mqtt2serial work to get past the difficulty of interfacing with the raspberry pi with minimal hardware and good robustness. Thanks again.
